import pandas as pd

def get_pitcher_profile_data():
  return pd.DataFrame({
    'pitcher_id': [
      1,
      2,
      3,
      4,
      5,
      6,
      7
    ],
    'name': [
      'Dustin May',
      'Jack Flaherty',
      'Lazaro Estrada',
      'Anthony Kay',
      'Chad Patrick',
      'Tony Bennet',
      'Seth Lugo'
    ],
    'pitcher_strike_K_percent': [0.42, 0.32, 0.15, 0.25, 0.43, 0.22, 0.10],
    'elite_strikeout_K': [True, True, False, False, True, False, False],
    'pitcher_k_9': [7.34, 6.25, 7.45, 7.32, 4.12, 4.14, 5.23],
    'pitcher_era': [3.45, 2.55, 3.89, 3.30, 1.34, 1.50, 2.01],
    'projected_matchup_strikeouts': [1.34, 2.45, 4.56, 3.56, 4.76, 5.56, 4.45],
    'pitcher_dominance_index': [1.34, 2.45, 2.56, 1.56, 2.76, 3.56, 2.45]
  })

def get_batter_profile_data():
  return pd.DataFrame({
    'batter_id': [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32,
      33,
      34,
      35,
      36
    ],
    'team': [
      'STL',
      'STL',
      'STL',
      'STL',
      'STL',
      'STL',
      'STL',
      'STL',
      'STL',
      'DET',
      'DET',
      'DET',
      'DET',
      'DET',
      'DET',
      'DET',
      'DET',
      'DET',
      'CWS',
      'CWS',
      'CWS',
      'CWS',
      'CWS',
      'CWS',
      'CWS',
      'CWS',
      'CWS',
      'KCR',
      'KCR',
      'KCR',
      'KCR',
      'KCR',
      'KCR',
      'KCR',
      'KCR',
      'KCR'
    ],
    'position': [
      '2B',
      'OF',
      '1B',
      '3B',
      'OF',
      'SS',
      'OF',
      'C',
      'OF',
      '3B',
      'SS',
      '2B',
      'OF',
      'OF',
      'C',
      'OF',
      '1B',
      'OF',
      '2B',
      'SS',
      '3B',
      'OF',
      'OF',
      '1B',
      'OF',
      'C',
      'OF',
      '3B',
      'SS',
      '1B',
      'C',
      'OF',
      'OF',
      '2B',
      'OF',
      'OF'
    ],
    'name': [
      'J. Wetherholt',
      'Ivan Herrera',
      'A. Burleson',
      'Nolan Gorman',
      'J. Walker',
      'T. Saggese',
      'N. Church',
      'Pedro Pages',
      'Victor Scott',
      'Colt Keith',
      'K. McGonigle',
      'G. Torres',
      'K. Carpenter',
      'Riley Greene',
      'D. Dingler',
      'Z. McKinstry',
      'S. Torkelson',
      'P. Meadows',
      'C. Meidroth',
      'C. Montgomery',
      'M. Vargas',
      'A. Benintendi',
      'Austin Hays',
      'M. Murakami',
      'E. Pereira',
      'Edgar Quero',
      'L. Acuna',
      'M. Garcia',
      'Bobby Witt',
      'V. Pasquantino',
      'S. Perez',
      'Lane Thomas',
      'J. Caglianone',
      'J. India',
      'I. Collins',
      'Kyle Isbel'
    ],
    'opposing_team': [
      'DET',
      'DET',
      'DET',
      'DET',
      'DET',
      'DET',
      'DET',
      'DET',
      'DET',
      'STL',
      'STL',
      'STL',
      'STL',
      'STL',
      'STL',
      'STL',
      'STL',
      'STL',
      'KCR',
      'KCR',
      'KCR',
      'KCR',
      'KCR',
      'KCR',
      'KCR',
      'KCR',
      'KCR',
      'CWS',
      'CWS',
      'CWS',
      'CWS',
      'CWS',
      'CWS',
      'CWS',
      'CWS',
      'CWS'
    ],
    'batting_order': [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
    ]
  })

def get_starting_players_data():
  return pd.DataFrame({
    'Starting Lineup': [
      'D. May R',
      'Jack Flaherty R',
      'Lazaro Estrada R',
      'Anthony Kay L',
      'Chad Patrick R',
      'Tony Bennet L',
      'Seth Lugo R',
      '2B J. Wetherholt L',
      'DH Ivan Herrera R',
      '1B A. Burleson L',
      '3B Nolan Gorman L',
      'RF J. Walker R',
      'SS T. Saggese R',
      'LF N. Church L',
      'C Pedro Pages R',
      'CF Victor Scott L',
      '3B Colt Keith L',
      'SS K. McGonigle L',
      '2B G. Torres R',
      'DH K. Carpenter L',
      'LF Riley Greene L',
      'C D. Dingler R',
      'RF Z. McKinstry L',
      '1B S. Torkelson R',
      'CF P. Meadows L',
      'LINE STL -163',
      'O/U 8.0 Runs',
      '2B C. Meidroth R',
      'SS C. Montgomery L',
      '3B M. Vargas R',
      'DH A. Benintendi L',
      'LF Austin Hays R',
      '1B M. Murakami L',
      'RF E. Pereira R',
      'C Edgar Quero S',
      'CF L. Acuna R',
      '3B M. Garcia R',
      'SS Bobby Witt R',
      '1B V. Pasquantino L',
      'C S. Perez R',
      'RF Lane Thomas R',
      'DH J. Caglianone L',
      '2B J. India R',
      'LF I. Collins S',
      'CF Kyle Isbel L',
      'LINE CWS -163',
      'O/U 6.0 Runs',
    ]
  })

def get_mlb_national_league_averages():
  return pd.DataFrame({
    'league_pitcher_k_bb_average': [
      0.29
    ]
  })

def get_ball_park_factors():
  return pd.DataFrame({
    'Rk': [6, 13, 14, 16, 20, 22, 24],
    'Team': ['KCR', 'DET', 'STL', 'TOR', 'CWS', 'MIL', 'CHC'],
    'Park Factor': [101, 100, 97, 100, 99, 97, 97]
  })

def get_pitcher_ball_park_profile():
  return pd.DataFrame({
    'position': ['SP', 'SP', 'SP'],
    'name_id': ['D. May (4892886)', 'Chad Patrick (4892890)', 'Tony Bennet (4892891)'],
    'name': ['D. May', 'Chad Patrick', 'Tony Bennet'],
    'team': ['STL', 'MIL', 'CHC'],
    'salary': [10900, 9800, 9500],
    'Rk': [14, 22, 24],
    'Team': ['STL', 'MIL', 'CHC'],
    'Park Factor': [97, 97, 97]
  })

def get_pitcher_non_ball_park_profile_dk():
  return pd.DataFrame({
    'position':['SP', 'SP', 'SP'],
    'name_id': ['Lazaro Estrada (4892888)', 'Chad Patrick (4892890)', 'Tony Bennet (4892891)'],
    'name': ['Lazaro Estrada', 'Chad Patrick', 'Tony Bennet'],
    'team': ['TOR', 'MIL', 'CHC'],
  })

def get_official_depth_chart():
  return pd.DataFrame({
    'starting_lineup': [
      'J. Wetherholt',
      'Ivan Herrera',
      'A. Burleson',
      'Nolan Gorman',
      'J. Walker',
      'T. Saggese',
      'N. Church',
      'Pedro Pages',
      'Victor Scott',
      'Colt Keith',
      'K. McGonigle',
      'G. Torres',
      'K. Carpenter',
      'Riley Greene',
      'D. Dingler',
      'Z. McKinstry',
      'S. Torkelson',
      'P. Meadows',
      'C. Meidroth',
      'C. Montgomery',
      'M. Vargas',
      'A. Benintendi',
      'Austin Hays',
      'M. Murakami',
      'E. Pereira',
      'Edgar Quero',
      'L. Acuna',
      'M. Garcia',
      'Bobby Witt',
      'V. Pasquantino',
      'S. Perez',
      'Lane Thomas',
      'J. Caglianone',
      'J. India',
      'I. Collins',
      'Kyle Isbel'
    ],
    'lineup_order': [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
    ]
  })

def get_pitcher_stats():
  pitching_stats = pd.read_csv('test/sample_data/test_pitching_stats.csv', encoding='latin1')
  return pd.DataFrame(pitching_stats)

def get_statcast_pitching_stats():
  pitching_stats = pd.read_csv('test/sample_data/test_statcast_pitcher_percentile_ranks.csv')
  return pd.DataFrame(pitching_stats)

def get_league_pitching_averages():
  league_pitching_stats = pd.read_csv('test/sample_data/test_league_pitching_average.csv')
  return pd.DataFrame(league_pitching_stats)

def get_batting_stats():
  batting_stats = pd.read_csv('test/sample_data/test_batting_stats.csv', encoding='cp1252')
  return pd.DataFrame(batting_stats)

def get_league_batting_averages():
  league_pitching_stats = pd.read_csv('test/sample_data/test_league_batting_average.csv')
  return pd.DataFrame(league_pitching_stats)

def get_statcast_dataset():
  statcast_stats = pd.read_csv('test/sample_data/test_statcast_stats.csv')
  return pd.DataFrame(statcast_stats)