import services.nfl_services as nfl_services
import services.pga_services as pga_services

nfl_services.get_nfl_team_offense_stats()
nfl_services.get_nfl_player_snap_count()
nfl_services.get_nfl_team_defense_stats()
nfl_services.get_overall_weighted_defensive_average()
nfl_services.get_nfl_fantasy_points_leaders()
nfl_services.get_nfl_dk_salary_data()
nfl_services.get_nfl_odds()
nfl_services.get_nfl_teams()
nfl_services.get_nfl_fantasy_projections()
pga_services.player_expected_score()
pga_services.player_expected_score_with_course_difficulty()